/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenapetha_institute;

import nenapetha_institute.kameshi.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class sample extends javax.swing.JFrame {

    int Xmouse;
    int Ymouse;
    String newpath;
    
    /**
     * Creates new form sample_2
     */
    public sample() {
          
        setDateAndTime();
        initComponents();
        //loadImage();
        //loadname();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        menuItem1 = new java.awt.MenuItem();
        menuItem2 = new java.awt.MenuItem();
        maximum = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_settings = new javax.swing.JButton();
        btn_forward = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        lbl_panelname = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        lbl_user_name = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_date_auto = new javax.swing.JLabel();
        lbl_time_auto = new javax.swing.JLabel();
        Date_Time_Spacer = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Draggable_Frame = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        menuItem1.setLabel("menuItem1");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItem1);

        menuItem2.setLabel("menuItem2");
        popupMenu1.add(menuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maximum.setToolTipText("Maximize");
        maximum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximumMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maximumMousePressed(evt);
            }
        });
        maximum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                maximumPropertyChange(evt);
            }
        });
        getContentPane().add(maximum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 50));

        Minimize.setToolTipText("Minimize");
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 30, 30));

        Close.setToolTipText("Close");
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 30, 30));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/back-icon_1.png"))); // NOI18N
        btn_back.setToolTipText("Back");
        btn_back.setBorder(null);
        btn_back.setContentAreaFilled(false);
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, 50, 50));

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/home-icon.png"))); // NOI18N
        btn_home.setToolTipText("Home");
        btn_home.setBorder(null);
        btn_home.setContentAreaFilled(false);
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 64, 50, 50));

        btn_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/Settings-icon.png"))); // NOI18N
        btn_settings.setToolTipText("Settings");
        btn_settings.setBorder(null);
        btn_settings.setContentAreaFilled(false);
        btn_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 70, 60, 60));

        btn_forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/forward-icon.png"))); // NOI18N
        btn_forward.setToolTipText("Forward");
        btn_forward.setBorder(null);
        btn_forward.setContentAreaFilled(false);
        btn_forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forwardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 64, 50, 50));

        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/Add.png"))); // NOI18N
        btn_add.setToolTipText("Add");
        btn_add.setBorder(null);
        btn_add.setContentAreaFilled(false);
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 160, 140, 130));

        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/update.png"))); // NOI18N
        btn_update.setToolTipText("Update");
        btn_update.setBorder(null);
        btn_update.setContentAreaFilled(false);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 289, 140, 130));

        btn_search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/search.png"))); // NOI18N
        btn_search.setToolTipText("Search");
        btn_search.setBorder(null);
        btn_search.setContentAreaFilled(false);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 570, 140, 120));

        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Butttons/Delete.png"))); // NOI18N
        btn_del.setToolTipText("Delete");
        btn_del.setBorder(null);
        btn_del.setContentAreaFilled(false);
        getContentPane().add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 430, 140, 120));

        lbl_panelname.setBackground(new java.awt.Color(204, 204, 204));
        lbl_panelname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_panelname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_panelname.setText("User Management");
        getContentPane().add(lbl_panelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 40));

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1099397991_21000054.jpg"))); // NOI18N
        lbl_image.setToolTipText("User Image");
        getContentPane().add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 120, 80));

        lbl_user_name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_user_name.setForeground(new java.awt.Color(102, 102, 102));
        lbl_user_name.setText("Kameshi");
        lbl_user_name.setToolTipText("Logged As");
        getContentPane().add(lbl_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 72, 80, 50));

        lbl_welcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(0, 153, 204));
        lbl_welcome.setText("Welcome");
        getContentPane().add(lbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, 30));

        lbl_date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setText("Date : ");
        getContentPane().add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 745, -1, -1));

        lbl_time.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setText("Time : ");
        getContentPane().add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 745, -1, -1));

        lbl_date_auto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_date_auto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_date_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 743, 70, 20));

        lbl_time_auto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_time_auto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_time_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 743, 70, 20));

        Date_Time_Spacer.setForeground(new java.awt.Color(255, 255, 255));
        Date_Time_Spacer.setText("|");
        getContentPane().add(Date_Time_Spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 745, 10, -1));

        Background.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        Draggable_Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All.jpg"))); // NOI18N
        Draggable_Frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Draggable_FrameMousePressed(evt);
            }
        });
        Draggable_Frame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Draggable_FrameMouseDragged(evt);
            }
        });
        getContentPane().add(Draggable_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(user_management.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void Draggable_FrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Draggable_FrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - Xmouse, y - Ymouse);
    }//GEN-LAST:event_Draggable_FrameMouseDragged

    
    
    
    private void Draggable_FrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Draggable_FrameMousePressed
        Xmouse = evt.getX();
        Ymouse = evt.getY();
    }//GEN-LAST:event_Draggable_FrameMousePressed

    private void maximumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximumMouseClicked
        //this.setExtendedState(this.MAXIMIZED_BOTH); 
//        this.setPreferredSize(new Dimension(1366, 768));
        // myFrame.setExtendedState(myFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        Rectangle bounds = getMaximizedBounds(); // set your maximized bounds
        this.setMaximizedBounds(bounds);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_maximumMouseClicked

    private void maximumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_maximumPropertyChange
        // TODO add your handling code here:


    }//GEN-LAST:event_maximumPropertyChange

    private void maximumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximumMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_maximumMousePressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_formFocusGained

    private void btn_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingsActionPerformed
 

    }//GEN-LAST:event_btn_settingsActionPerformed

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void btn_forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_forwardActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Date_Time_Spacer;
    private javax.swing.JLabel Draggable_Frame;
    private javax.swing.JLabel Minimize;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_forward;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_settings;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_date_auto;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_panelname;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_time_auto;
    private javax.swing.JLabel lbl_user_name;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel maximum;
    private java.awt.MenuItem menuItem1;
    private java.awt.MenuItem menuItem2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
    
    
  

    Date d;
    SimpleDateFormat sdf;
    private void setDateAndTime() {
        
        Timer t=new Timer(1000, new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
         
                   d=new Date();
                   sdf=new SimpleDateFormat("yyyy-MM-dd");
                   lbl_date_auto.setText(sdf.format(d));
                   sdf=new SimpleDateFormat("HH:mm:ss");
                   lbl_time_auto.setText(sdf.format(d));
               }
           });
           t.start();
    
    }
}




    
